### ISSUE TITLE
Not supported in older versions of Node?

### ISSUE THREAD

**Issue by simevidas** [surma/http2-push-detect#1]
I’m not sure how to interpret this error:

![capture](https://cloud.githubusercontent.com/assets/716405/16940093/93276bea-4d87-11e6-8fd1-e53dc3711281.JPG)

I have Node v4.3.1 on my local machine. Does this mean that I would have to update it in order to run your tool? 😅

**Comment by surma** [comment]
Oooh, I totally forgot about non-bleeding edge node! Thanks for letting me know, I’ll backport the code :)

**Comment by surma** [comment]
Fixed in 694c190a9ac9f3a8a96a355624cb0a87e9d3fbb6

<img width="888" alt="screenshot 2016-07-19 11 53 30" src="https://cloud.githubusercontent.com/assets/234957/16947538/967854f6-4da7-11e6-9c67-0a75c6440ea3.png">
