### ISSUE TITLE
Push detect "hangs" when run against https://flat.io

### ISSUE THREAD

**Issue by ithinkihaveacat** [surma/http2-push-detect#2]
Running `http2-push-detect` against `https://flat.io` takes almost exactly 3 minutes to return: 

``` sh
$ time http2-push-detect https://flat.io
      180.33 real         0.16 user         0.02 sys
```

Is this expected?

**Comment by surma** [comment]
It will take as long as the HTTP/2 connection is being kept open by the server. I can’t close it as pushes could come through any time. AFAICT, this would be a misconfigured server and it’s working as intendend.
